### ISSUE TITLE
great previews, but doesn't save

### ISSUE THREAD

**Issue by mzecast** [serranoycandela/geo_value_functions#3]
I find the plugin great in previewing functions, but it can't save results! On saving, it stops forever, and you have to terminate QGIS in the task manager. Any additional configuration needed?
![error_gvf](https://user-images.githubusercontent.com/80954016/111877729-7f628a80-899c-11eb-8dbb-dd8a669449fb.jpg)
Many thanks!

**Comment by serranoycandela** [comment]
I am super happy that someone is using the plugin!
Ill try to help you
The strategy for a smoth visualization is not to calculate any raster while moving function parameters but just apply the inverse function to the color scale. So no actual raster is calculated until you click on Result Layer.
I tested it with a 34511 by 22051 cells raster with Int16 type of cell, and it takes 2 minutes to calculate the raster, maybe it just needs time?
If you could share with me the raster you are working on to test it my self would be nice

**Comment by mzecast** [comment]
Thank you very much for your reply and support; I'd understood get the new "geo value function" raster by clicking on "result layer" indeed.

Now I've changed my raster into Int16 (originally float32), but nothing happens, and I've to restart QGIS again. I've attached it so you can check if there is something wrong with it.

Some hints that may tell you what's wrong with saving the new raster (I thought into might help, I don't know):
•	The square button to change the new raster's destination folder doesn't work; nothing happens when I click on it.
•	If I change the prefix for the new raster, the "/" symbol in the path to the folder becomes "\".

Again, thanks a lot for the plugin, and I hope it helps.

**Comment by serranoycandela** [comment]
@mzecast I dont see any attached raster
maybe use an external link of dropbox for example?
the ... button handler was not implemented in the experimental version i uploaded. But im working on it, so next version will have it :)

**Comment by mzecast** [comment]
Sorry, here you are
[altitude.zip](https://github.com/serranoycandela/geo_value_functions/files/6180253/altitude.zip)
Hope it functions

**Comment by serranoycandela** [comment]
ok, i tested it with your raster and it took like 2 seconds to produce result raster
so the problem is not the layer

[f_altitude.zip](https://github.com/serranoycandela/geo_value_functions/files/6183278/f_altitude.zip)

May be the problem is the disk is E: or maybe the problem is that it doent work properly under different os or qgis version
so lets try to identify the problem, what operating system are you using what version of qgis and how much ram you have?

**Comment by mzecast** [comment]
Hi,
I've moved to a C: folder and things are still the same :(
I have Windows 10, 8 Gb RAM, it is usually not a problem...
Thanks

**Comment by serranoycandela** [comment]
Lets make a zoom meeting to try to solve it?
I can do it any time before 4pm México time today, or at any hour tomorrow

**Comment by mzecast** [comment]
That was great, thanks again. If it's okay with you, I'll send you the link right now

**Comment by serranoycandela** [comment]
ok lets do it
my mail is serranoycandela@gmail.com

**Comment by serranoycandela** [comment]
The plugin cant save results in QGIS 3.18
