### ISSUE TITLE
Please rephrase About and Description

### ISSUE THREAD

**Issue by pcav** [serranoycandela/geo_value_functions#6]
Please note that the description field in metadata is meant as a very short description of the plugin (usually one line), whereas the about can be used for a lengthy description. Please rephrase both. Thanks.

**Comment by serranoycandela** [comment]
Ok, I rephrased description to make it short,
what should I change in about?
Thanks

**Comment by pcav** [comment]
Thanks - shorten one, eventually adding the removed content to the other

**Comment by serranoycandela** [comment]
ok, I uploaded new zip
